#!/usr/bin/env python
import rospy

import tf2_ros
from geometry_msgs.msg import Transform, TransformStamped

rospy.init_node('zed2_imu_transform_broadcaster')

tf_prefix_param = rospy.search_param("tf_prefix")
if tf_prefix_param is None:
    tf_prefix = ""
else:
    tf_prefix = rospy.get_param(tf_prefix_param)

broadcaster = tf2_ros.StaticTransformBroadcaster()
imu_transform = TransformStamped()

imu_transform.header.stamp = rospy.get_rostime()
imu_transform.header.frame_id = (tf_prefix + "/zed2_left_camera_frame").strip('/')
imu_transform.child_frame_id = (tf_prefix + "/zed2_imu_link").strip('/')

imu_transform.transform = rospy.wait_for_message("zed2/left_cam_imu_transform", Transform)

broadcaster.sendTransform(imu_transform)
rospy.spin()